version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - APP_VERSION=1.0
    image: symfony_app:1.0
    container_name: symfony_app
    ports:
      - "8000:8000"
    volumes:
      - ./:/var/www/html
    environment:
      - APP_ENV=dev
      - APP_DEBUG=1
      - DATABASE_URL=mysql://symfony:symfony@db:3306/symbook?serverVersion=8.0
    depends_on:
      - db
    command: bash -c "
      chmod -R 777 var &&
      rm -rf var/cache/* &&
      until php bin/console doctrine:query:sql 'SELECT 1' >/dev/null 2>&1; do
        echo 'Waiting for database...';
        sleep 2;
      done &&
      php bin/console doctrine:migrations:migrate --no-interaction &&
      symfony server:start --port=8000 --no-tls --allow-http --allow-all-ip"

  db:
    image: mysql:8.0
    container_name: symfony_db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: symbook
      MYSQL_USER: symfony
      MYSQL_PASSWORD: symfony
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: symfony_phpmyadmin
    restart: unless-stopped
    ports:
      - "8081:80"
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_USER: symfony
      PMA_PASSWORD: symfony
    depends_on:
      - db

volumes:
  db_data:
    name: symbook_db_data
